apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: register-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/panthangiEshwary/gitops-register-app.git'
    targetRevision: HEAD
    path: '.'  # root of the repo where deployment.yaml and service.yaml exist
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

